routes/web.php
				Route::post('/store',"Backend\User\BachelorCardController@store")->name('user-cards-store');

				Route::get('/booking/{id}',[
					'uses'=>'Backend\User\BachelorCardController@booking',
					'as'=>'card-user-booking'
				]);

				Route::get('/show',"Backend\User\BachelorCardController@show")->name('user-cards-show');
				Route::get('/edit/{id}',"Backend\User\BachelorCardController@edit")->name('user-cards-edit');
				Route::post('/update/{id}',"Backend\User\BachelorCardController@update")->name('user-cards-update');
				Route::post('/delete/{id}',"Backend\User\BachelorCardController@destroy")->name('user-cards-destroy'); 
			});




		Route::group(['prefix'=>'sub-lets'],function(){
				Route::get('/', [
					'uses' => 'Backend\User\SubletController@index',
					'as' => 'sub-lets-user-index'
				]);

				Route::get('is-confirmed', [
					'uses' => 'Backend\User\SubletController@confirmed',
					'as' => 'sub-lets-user-confirmed'
				]);

				Route::get('/create', [
					'uses' => 'Backend\User\SubletController@create',
					'as' => 'sub-lets-user-create'
				]);

				Route::post('/store', [
					'uses' => 'Backend\User\SubletController@store',
					'as' => 'sub-lets-user-store'
				]);
				Route::get('/edit/{id}',[
					'uses'=>'Backend\User\SubletController@edit',
					'as'=>'sub-lets-user-edit'
				]);

				Route::post('/update/{id}',[
					'uses'=>'Backend\User\SubletController@update',
					'as'=>'sub-lets-user-update'
				]);

				Route::get('/show/{id}',[
					'uses'=>'Backend\User\SubletController@show',
					'as'=>'sub-lets-user-show'
				]);

				Route::get('/booking/{id}',[
					'uses'=>'Backend\User\SubletController@booking',
					'as'=>'sublet-user-booking'
				]);

	        });
});

// user route end


//only admin route start
Route::group(['prefix'=>'admin'],function(){

		Route::get('/', [
			'uses' => 'Backend\Admin\AdminController@dashboard',
			'as' => 'admin.dashboard'
		]);
		//admin registration and verification
	    Route::get('/register/submit',[
	    	'uses'=>'Auth\Admin\RegisterController@showRegistrationForm',
	    	'as'=>'admin.register.submit'
	    ]);
		Route::post('/register',[
			'uses'=>'Auth\Admin\RegisterController@register',
			'as'=>'admin.register'
		]);
		Route::get('/token/{token}',[
			'uses'=>'Backend\AdminVerificationController@verify',
			'as'=>'admin.verification'
		]);
	    //admin login and logout
		Route::get('/login',[
			'uses'=>'Auth\Admin\LoginController@showLoginForm',
			'as'=>'admin.login'
		]);

		Route::post('/login/submit',[
			'uses'=>'Auth\Admin\LoginController@login',
			'as'=>'admin.login.submit'
		]);

		Route::post('/logout',[
			'uses'=>'Auth\Admin\LoginController@logout',
			'as'=>'admin.logout'
	    ]);

	    //admin Forgotpassword and reset password
		Route::post('/password/email',[
			'uses'=>'Auth\Admin\ForgotPasswordController@sendResetLinkEmail',
			'as'=>'admin.password.email'
		]);
		Route::get('/password/reset',[
			'uses'=>'Auth\Admin\ForgotPasswordController@showLinkRequestForm',
			'as'=>'admin.password.request'
		]);
		Route::get('/password/reset/{token}',[
			'uses'=>'Auth\Admin\ResetPasswordController@showResetForm',
			'as'=>'admin.password.reset'
		]);
		Route::post('/password/reset',[
			'uses'=>'Auth\Admin\ResetPasswordController@reset',
			'as'=>'admin.password.reset.post'
		]);

		Route::resource('cities','Backend\Admin\CityController');
		Route::resource('thanas','Backend\Admin\ThanaController');
		Route::resource('wards','Backend\Admin\WardController');

		//for categories
	    Route::group(['prefix'=>'categories'],function(){

		    Route::get('/',"Backend\Admin\CategoryController@index")->name('categories.index');
		    Route::get('/create',"Backend\Admin\CategoryController@create")->name('categories.create');
		    Route::post('/store',"Backend\Admin\CategoryController@store")->name('categories.store');
		    Route::get('/show/{id}',"Backend\Admin\CategoryController@show")->name('categories.show');
		    Route::get('/edit/{id}',"Backend\Admin\CategoryController@edit")->name('categories.edit');
		    Route::post('/update/{id}',"Backend\Admin\CategoryController@update")->name('categories.update');
		    Route::post('/delete/{id}',"Backend\Admin\CategoryController@delete")->name('categories.delete');
		    Route::get('/categories-show/{id}',"Backend\Admin\FamilyController@categories_show")->name('categories-show');
		});




	    Route::group(['prefix'=>'cards'],function(){
	            Route::get('/',"Backend\Admin\BachelorCardController@index")->name('admin-cards-index');
				Route::get('/create',"Backend\Admin\BachelorCardController@create")->name('admin-cards-create');
				Route::post('/store',"Backend\Admin\BachelorCardController@store")->name('admin-cards-store');

				Route::get('/show',"Backend\Admin\BachelorCardController@show")->name('admin-cards-show');
				Route::get('/edit/{id}',"Backend\Admin\BachelorCardController@edit")->name('admin-cards-edit');
				Route::post('/update/{id}',"Backend\Admin\BachelorCardController@update")->name('admin-cards-update');
				Route::post('/delete/{id}',"Backend\Admin\BachelorCardController@destroy")->name('admin-cards-destroy');
		});

		Route::group(['prefix'=>'comments'],function(){ 

				Route::post('/comment/store', [
					'uses' => 'Backend\Admin\CommentController@store',
					'as' => 'admin-comment-store'
				]);


	    });




	    Route::group(['prefix'=>'families'],function(){
				Route::get('/pending', [
					'uses' => 'Backend\Admin\FamilyController@pending',
					'as' => 'families-admin-pending'
				]);

				Route::get('confirm', [
					'uses' => 'Backend\Admin\FamilyController@confirm',
					'as' => 'families-admin-confirm'
				]);

				Route::get('/complete', [
					'uses' => 'Backend\Admin\FamilyController@complete',
					'as' => 'families-admin-complete'
				]);

				Route::get('/create', [
					'uses' => 'Backend\Admin\FamilyController@create',
					'as' => 'families-admin-create'
				]);

				Route::post('/store', [
					'uses' => 'Backend\Admin\FamilyController@store',
					'as' => 'families-admin-store'
				]);
				Route::get('/edit/{id}',[
					'uses'=>'Backend\Admin\FamilyController@edit',
					'as'=>'families-admin-edit'
				]);

				Route::post('/update/{id}',[
					'uses'=>'Backend\Admin\FamilyController@update',
					'as'=>'families-admin-update'
				]);

				Route::get('/show/{id}',[
					'uses'=>'Backend\Admin\FamilyController@show',
					'as'=>'families-admin-show'
				]);

				Route::post('/comment/store', [
					'uses' => 'Backend\Admin\FamilyCommentController@comment_store',
					'as' => 'families-admin-comment-store'
				]);

				Route::post('/families/confirmed/{id}', [
					'uses' => 'Backend\Admin\FamilyController@is_Confirmed',
					'as' => 'admin-family-confirmed'
				]);



	});
	    Route::group(['prefix'=>'bechelors'],function(){
				Route::get('/pending', [
					'uses' => 'Backend\Admin\BechelorController@pending',
					'as' => 'bechelors-admin-pending'
				]);

				Route::get('confirm', [
					'uses' => 'Backend\Admin\BechelorController@confirm',
					'as' => 'bechelors-admin-confirm'
				]);

				Route::get('complete', [
					'uses' => 'Backend\Admin\BechelorController@complete',
					'as' => 'bechelors-admin-complete'
				]);

				Route::get('/create', [
					'uses' => 'Backend\Admin\BechelorController@create',
					'as' => 'bechelors-admin-create'
				]);

				Route::post('/store', [
					'uses' => 'Backend\Admin\BechelorController@store',
					'as' => 'bechelors-admin-store'
				]);
				Route::get('/edit/{id}',[
					'uses'=>'Backend\Admin\BechelorController@edit',
					'as'=>'bechelors-admin-edit'
				]);

				Route::post('/update/{id}',[
					'uses'=>'Backend\Admin\BechelorController@update',
					'as'=>'bechelors-admin-update'
				]);

				Route::get('/show/{id}',[
					'uses'=>'Backend\Admin\BechelorController@show',
					'as'=>'bechelors-admin-show'
				]);

				Route::post('/comment/store', [
					'uses' => 'Backend\Admin\BechelorCommentController@comment_store',
					'as' => 'bechelors-admin-comment-store'
				]);

				Route::post('/bachelors/confirmed/{id}', [
					'uses' => 'Backend\Admin\BechelorController@is_Confirmed',
					'as' => 'admin-bachelor-confirmed'
				]);

	        });


	    Route::group(['prefix'=>'sublets'],function(){
				Route::get('/pending', [
					'uses'=>'Backend\Admin\SubletController@pending',
					'as' => 'sublets-admin-pending'
				]);

				Route::get('confirm', [
					'uses'=>'Backend\Admin\SubletController@confirm',
					'as' => 'sublets-admin-confirm'
				]);

				Route::get('/complete', [
					'uses'=>'Backend\Admin\SubletController@complete',
					'as' => 'sublets-admin-complete'
				]);


				Route::get('/create', [
					'uses' => 'Backend\Admin\SubletController@create',
					'as' => 'sublets-admin-create'
				]);

				Route::post('/store', [
					'uses' => 'Backend\Admin\SubletController@store',
					'as' => 'sublets-admin-store'
				]);
				Route::get('/edit/{id}',[
					'uses'=>'Backend\Admin\SubletController@edit',
					'as'=>'sublets-admin-edit'
				]);

				Route::post('/update/{id}',[
					'uses'=>'Backend\Admin\SubletController@update',
					'as'=>'sublets-admin-update'
				]);

				Route::get('/show/{id}',[
					'uses'=>'Backend\Admin\SubletController@show',
					'as'=>'sublets-admin-show'
				]);

				Route::post('/comment/store', [
					'uses' => 'Backend\Admin\SubletCommentController@comment_store',
					'as' => 'sublets-admin-comment-store'
				]);

				Route::post('/sublets/confirmed/{id}', [
					'uses' => 'Backend\Admin\SubletController@is_Confirmed',
					'as' => 'admin-sublets-confirmed'
				]);
	        });

	        Route::group(['prefix'=>'comments'],function(){

				Route::post('/comment/store', [
					'uses' => 'Backend\Admin\CommentController@store',
					'as' => 'admin-comment-store'
				]);


			});


	    Route::group(['prefix'=>'orders'],function(){


					Route::get('/families', [
						'uses' => 'Backend\Admin\OrderController@family_index',

app/Models/Admin/City.php
<?php

namespace App\Models\Admin;

use Illuminate\Database\Eloquent\Model;

class City extends Model
{
    protected $fillable = ['name','bangla_name','latitude','longitude'];
}

app/Http/Controllers/Backend/Admin/CityController.php
<?php

namespace App\Http\Controllers\Backend\admin;

use Cornford\Googlmapper\Facades\MapperFacade as Mapper;
use Illuminate\Http\Request;
use App\Models\Admin\City;
use App\Http\Controllers\Controller;

class CityController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth:admin');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $cities =City::orderBy('id','desc')->get();
        return view('Backend.admin.cities.index',compact('cities'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('Backend.admin.cities.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
          'name'=>'required|max:50|min:5',
        ]);

        $cities=new City();
        $cities->name=$request->name;
        $cities->bangla_name=$request->bangla_name;
        $cities->latitude=$request->latitude;
        $cities->longitude=$request->longitude;
        $cities->save();
        if(!is_null($cities)){
          session()->flash('success','City create Successfully!!');
          return redirect()->route('cities.index');
        }else{
          session()->flash('success','Some Error Occer!!');
          return back();
        }

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
         $cities=City::findOrFail($id);
        $latitude=$cities->latitude;
        $longitude=$cities->longitude;


        Mapper::map($latitude,$latitude, ['zoom' => 10, 'markers' => ['title' => 'My Location', 'animation' => 'DROP'], 'clusters' => ['size' => 10, 'center' => true, 'zoom' => 20]]);
         return view('Backend.admin.cities.show',compact('cities'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $cities = City::findOrFail($id);
        if(!is_null($cities)){
            return view('Backend.admin.cities.edit',compact('cities'));
        }else{
            return back();
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
          //dd($id);
          $this->validate($request,[
            'name'=>'required|max:50|min:5',
          ]);

          $cities=City::findOrFail($id);
          $cities->name=$request->name;
          $cities->bangla_name=$request->bangla_name;
          $cities->latitude=$request->latitude;
          $cities->longitude=$request->longitude;
          $cities->update();
          if(!is_null($cities)){
              session()->flash('success','City Update Successfully!!');
              return redirect()->route('cities.index');
          }else{
              session()->flash('sticky_error','Some Error Occer!!');
              return back();
          }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $cities=City::find($id);
        if(!is_null($cities))
        {
            $cities->delete();
            session()->flash('success','Product has delete Successfully');
            return back();
        }else{
            session()->flash('sticky_error','Some Error Occer');
            return back();
        }

    }
}

resources/views/backend/admin/cities/create.blade.php
@extends('Backend.admin.layouts.master')
@section('content')
<div class="card shadow mb-4">
            <div class="card-header py-3">
              <h1 class="text-center">City Create</h1>
            </div>
            <div class="card-body">
              <h1 class="text-right"><a href="{{route('cities.index')}}"><i class="fas fa-backward"></i></a></h1>
      <form method="POST" action="{{ route('cities.store') }}">
        @csrf
        <div class="form-group">
          <label for="name">City Name</label>
          <div class="form-input">
            <input type="text" class="form-control is-invalid form-control-sm" name="name" id="name" placeholder="Enter City name" value="" required>
            <div class="invalid-feedback">
              {{ ($errors->has('name')) ? $errors->first('name') : ''}}
            </div>
          </div>
        </div>
        <div class="form-group">
          <label for="bangla_name">City Bangla Name</label>
          <div class="form-input">
            <input type="text" class="form-control is-valid form-control-sm" name="bangla_name" id="bangla_name" placeholder="Enter City Bangla Name" value="">
            <div class="valid-feedback">
              {{ ($errors->has('bangla_name')) ? $errors->first('bangla_name') : ''}}
            </div>
          </div>
        </div>
        <div class="form-group">
          <label for="latitude">City Latitude</label>
          <div class="form-input">
            <input type="double" class="form-control" name="latitude" id="latitude" placeholder="Enter City latitude" value="">
            <div class="valid-feedback">
              {{ ($errors->has('latitude')) ? $errors->first('latitude') : ''}}
            </div>
          </div>
        </div>
        <div class="form-group">
          <label for="longitude">City Longitude</label>
          <div class="form-input">
            <input type="double" class="form-control"name="longitude" id="longitude" placeholder="Enter City longitude" value="">
            <div class="valid-feedback">
              {{ ($errors->has('longitude')) ? $errors->first('longitude') : ''}}
            </div>
          </div>
        </div>
        <button class="btn btn-primary" type="submit">Create</button>
      </form>
    </div>
  </div>
@endsection

resources/views/backend/admin/cities/edit.blade.php
@extends('Backend.admin.layouts.master')
@section('content')
<div class="card shadow mb-4">
            <div class="card-header py-3 text-center">
              <h1>City Edit</h1>
            </div>
            <div class="card-body">
              <h1 class="text-right"><a href="{{route('cities.index')}}"><i class="fas fa-backward"></i></a></h1>
              <div class="mt-2">
      <form method="POST" action="{{ route('cities.update',$cities->id) }}" >
        @csrf
        @method('PUT')
        <div class="form-group">
          <label for="name">City Name</label>
          <div class="form-input">
            <input type="text" class="form-control is-invalid form-control-sm" name="name" id="name" value="{{ $cities->name}}">
            <div class="invalid-feedback">
              {{ ($errors->has('name')) ? $errors->first('name') : ''}}
            </div>
          </div>
        </div>
        <div class="form-group">
          <label for="bangla_name">City Bangla Name</label>
          <div class="form-input">
            <input type="text" class="form-control is-valid form-control-sm" name="bangla_name" id="bangla_name" value="{{ $cities->bangla_name? $cities->bangla_name:'N\A'}}">
            <div class="valid-feedback">
              {{ ($errors->has('bangla_name')) ? $errors->first('bangla_name') : ''}}
            </div>
          </div>
        </div>
        <div class="form-group">
          <label for="latitude">City Latitude</label>
          <div class="form-input">
            <input type="double" class="form-control is-valid form-control-sm input-md" step="0.01" name="latitude" id="latitude" value="{{ $cities->latitude? $cities->latitude:'0.00'}}">
            <div class="valid-feedback">
              {{ ($errors->has('latitude')) ? $errors->first('latitude') : ''}}
            </div>
          </div>
        </div>
        <div class="form-group">
          <label for="longitude">City Longitude</label>
          <div class="form-input">
            <input type="double" class="form-control is-valid form-control-sm input-md"step="0.01" name="longitude" id="longitude" value="{{ $cities->longitude? $cities->longitude:'0.00'}}">
            <div class="valid-feedback">
              {{ ($errors->has('longitude')) ? $errors->first('longitude') : ''}}
            </div>
          </div>
        </div>
        <button class="btn btn-primary" type="submit">Update</button>
      </form>
    </div>
    </div>
<div class="col-sm-4">
  <div id="map">
  </div>
</div>
@endsection

resources/views/backend/admin/cities/index.blade.php
@extends('Backend.admin.layouts.master')

@section('content')

          <div class="card shadow mb-4">
            <div class="card-header py-3 text-center">
              <h1>City List</h1>
            </div>
            <div class="card-body">
              <h1 class="text-right"><a href="{{route('cities.create')}}"><i class="fas fa-plus-circle"></i></a></h1>
              <div class="table-responsive mt-2">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <caption>List of cities</caption>
                        <thead>
                          <tr>
                            <th>SL</th>
                            <th>Name</th>
                            <th>Bangla name</th>
                            <th>Latitude</th>
                            <th>Longitude</th>
                            <th>Show Details</th>
                            <th>Action</th>
                          </tr>
                        </thead>
                        <tbody>
                          <tr>
                            <div style="display: none;">{{$a=1}}</div>
                            @foreach($cities as $city)
                            <td>{{ $a++ }}</td>
                            <td>{{ $city->name }}</td>
                            <td>
                                @if($city->bangla_name)
                                <p>{{ $city->bangla_name}}</p>
                                @else
                                  <p>N/A</p>
                                @endif
                            </td>
                            <td>
                                @if($city->latitude)
                                <p>{{ $city->latitude}}</p>
                                @else
                                  <p>N/A</p>
                                @endif
                            </td>
                            <td>
                                @if($city->longitude)
                                <p>{{ $city->longitude}}</p>
                                @else
                                  <p>N/A</p>
                                @endif
                            </td>
                            <td>
                              <a href="{{route('cities.show', $city->id)}}" class="badge badge-primary">Show</a>
                            </td>
                            <td>
                              <a href="{{route('cities.edit', $city->id)}}" class="badge badge-warning">Edit</a>
                              <a href="#" onclick="return confirm('are you sure')">
                                <form class="pull-right form-inline" action="{{route('cities.destroy', $city->id)}}" method="POST">
                                  {{csrf_field()}}
                                  {{method_field('DELETE')}}
                                  <button class="badge badge-danger" type="submit">Delete</button>
                                </form>
                              </a>
                            </td>
                          </tr>
                          @endforeach
                        </tbody>
                      </table>
                    </div>
            </div>
          </div>

@endsection

resources/views/backend/admin/cities/show.blade.php
@extends('Backend.admin.layouts.master')

@section('content')
<div class="card shadow mb-4">
            <div class="card-body">
              <h1 class="text-right"><a href="{{route('cities.index')}}"><i class="fas fa-backward"></i></a></h1>
              <div class="mt-2">
      <div class="row">
        
        <div class="col-sm-6">
          <table class="table table-bordered"> 
          <thead> 
            <tr>
            <th>name</th> 
            <td> {{$cities->name}} </td> 
            </tr>
            <tr>
            <th>Bangla Name</th> 
            <td> {{$cities->bangla_name?$cities->bangla_name:'N\A'}} </td> 
            </tr>
            <tr>
            <th>Latitude</th> 
            <td> {{$cities->latitude?$cities->latitude:'N\A'}}</td> 
            </tr>
            <tr>
            <th>Longitude</th> 
            <td> {{$cities->longitude?$cities->longitude:'N\A'}} </td> 
            </tr>

          </thead>
        </table>
        </div>
        <div class="col-sm-6">
               <div style="height: 300px;">
                  {!! Mapper::render() !!}
               </div>
        </div>

      </div>
    </div>
  </div>
@endsection